#
# Global cost map to store configuration options specific to the global costmap to be used by the Global planner to generate a long-term plan.
# -The local planner uses the local costmap to generate a short-term plan. 
#
# ONLY the global costmap is configured to use a map while the local planner operates in the odometric frame.
# Setting the "static_map" parameter to true just means that you'll be taking an outside map source for navigation. 
# That map could come from SLAM or it could come from a source like the map_server. You shouldn't have to change the way you've configured the navigation stack to run SLAM, you'll just replace the map_server with your SLAM algorithm of choice.

global_costmap:
   global_frame: map                   # what coordinate frame the costmap should run in, in this case, we'll choose the /map frame
   robot_base_frame: robot_footprint   # the coordinate frame the costmap should reference for the base of the robot
   update_frequency: 10.0              # the frequency, in Hz, at which the costmap will run its update loop
   publish_frequency: 10.0             # The frequency in Hz for the map to be publish display information.
   width: 50.0                         # Width of global cost map in meters.
   height: 50.0                        # The height of the map in meters.
   resolution: 0.02                    # The resolution of the map in meters/cell. Hokuyo URG-04LX-UG01 laser scanner has metric resolution of 0.01mm
   static_map: true                    # whether or not the costmap should initialize itself based on a map served by the map_server. If you aren't using an existing map or map server, set the static_map parameter to false.
   rolling_window: false               # whether or not to use a rolling window version of the costmap. If the static_map parameter is set to true, this parameter must be set to false.
