#
# Trajectory Planner local cost map parameters
# The local planner uses the local costmap (specified by these params) to generate a short-term plan. 
# Remember: Only uses global_frame of ODOM, whereas Global params uses MAP
#

local_costmap:
   global_frame: odom
   robot_base_frame: robot_footprint
   transform_tolerance: 1.25
   update_frequency: 50.0              # The frequency in Hz for the map to be updated.
   publish_frequency: 50.0             # The frequency in Hz for the map to be publish display information.
   width: 25.0                         # The width of the local cost map in meters.
   height: 25.0                        # The height of the local cost map in meters.
   resolution: 0.05                    # (double, default 0.05) The resolution of the map in meters/cell.
   static_map: false
   rolling_window: true                # Whether or not to use a rolling window version of the costmap. If the static_map parameter is set to true, this parameter must be set to false.

